sudo: false

language: generic

addons:
  apt:
   packages:
   - libgmp-dev

services:
  - mysql

before_install:
  # Using compiler above sets CC to an invalid value, so unset it
  - unset CC

  # stack
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

before_script:
  - |
    mysql -u root <<EOF
    CREATE DATABASE PROJECTNAME_test;
    GRANT USAGE ON *.* TO PROJECTNAME@localhost IDENTIFIED BY 'PROJECTNAME';
    GRANT ALL PRIVILEGES ON PROJECTNAME_test.* TO PROJECTNAME@localhost;

script:
  - stack init --no-terminal
  - stack build --no-terminal --test --bench --install-ghc --haddock --no-haddock-deps --jobs 1

cache:
  directories:
    - $HOME/.stack
